### ISSUE TITLE
Not working getting  Cannot GET /detail

### ISSUE THREAD

**Issue by Gujjugaming2k** [avipatilpro/MXPlayer_API#3]
https://mxplayer-api.avipatilpro.repl.co/detail?type=movie&url=https://www.mxplayer.in/movie/watch-dj-hindi-dubbed-movie-online-3f7de5a6ca099b1e5ef3f8dfa888fc8c

**Comment by avipatilpro** [comment]
I Know Ill fix soon

**Comment by avipatilpro** [comment]
https://mxplayer-api.avipatilpro.repl.co/mx?type=movie&url=https://www.mxplayer.in/movie/watch-dj-hindi-dubbed-movie-online-3f7de5a6ca099b1e5ef3f8dfa888fc8c

**check your URL Format**

**Comment by Gujjugaming2k** [comment]
https://mxplayer-api.avipatilpro.repl.co/mx?type=movie&url=https://www.mxplayer.in/movie/watch-kanchana-3-movie-online-cae4d0f40ae9046775ea0072f093381a


not working

**Comment by avipatilpro** [comment]
Yahhh I'll fix it
